/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package maytinh.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import maytinh.controller.GiaodienchinhController;
import maytinh.util.XJdbc;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author PC
 */
public class manhinhchinhadmin extends javax.swing.JDialog implements GiaodienchinhController {

    /**
     * Creates new form manhinhchinh
     */
    public manhinhchinhadmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        lblTuNgay = new javax.swing.JLabel();
        txtTuNgay = new javax.swing.JTextField();
        lblDenNgay = new javax.swing.JLabel();
        txtDenNgay = new javax.swing.JTextField();
        lblLoai = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        btnLoc = new javax.swing.JButton();
        bieudo = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        cboKhoangTG = new javax.swing.JComboBox<>();
        pnlBieuDoBanChay = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(139, 195, 74));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Welcom !");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 102, 255));
        jPanel2.setRequestFocusEnabled(false);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        lblTuNgay.setText("Từ ngày");

        lblDenNgay.setText("Đến ngày");

        lblLoai.setText("Loại sản phẩm");

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Văn phòng", "Gaming  ", "Đồ họa", "Giá rẻ", " " }));

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocbtnLocActionPerformed(evt);
            }
        });

        bieudo.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bieudoLayout = new javax.swing.GroupLayout(bieudo);
        bieudo.setLayout(bieudoLayout);
        bieudoLayout.setHorizontalGroup(
            bieudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bieudoLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
        );
        bieudoLayout.setVerticalGroup(
            bieudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cboKhoangTG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hôm nay", "Hôm qua", "Tuần này", "Tháng này", "Tùy chọn" }));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTuNgay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDenNgay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboKhoangTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblLoai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(bieudo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDenNgay)
                    .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoai)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoc)
                    .addComponent(cboKhoangTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bieudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBieuDoBanChayLayout = new javax.swing.GroupLayout(pnlBieuDoBanChay);
        pnlBieuDoBanChay.setLayout(pnlBieuDoBanChayLayout);
        pnlBieuDoBanChayLayout.setHorizontalGroup(
            pnlBieuDoBanChayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        pnlBieuDoBanChayLayout.setVerticalGroup(
            pnlBieuDoBanChayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBieuDoBanChay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBieuDoBanChay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 112, 67));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Quản lý sản phẩm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 112, 67));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Quản lý kho hàng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 112, 67));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Quản lý bán hàng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 112, 67));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Quản lý khách hàng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 112, 67));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Quản lý đánh giá");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 112, 67));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Đổi mật khẩu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 112, 67));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Đăng xuất");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 153, 204));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Quản lý liên hệ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.showQuanLyKhachHangJDialog(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.showQuanlysanphamJDialog(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.showquanlykhoJDialog(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.showquanlybanhangJDialog(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.showquanlydanhgiaJDialog(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.showDoimatkhauJDialog(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất không?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            this.dispose();

            // Mở lại giao diện đăng nhập
            dangNhap login = new dangNhap(null, true);
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.showAdminLienHeJDialog(null);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnLocbtnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocbtnLocActionPerformed
        // TODO add your handling code here:
        xuLyKhoangThoiGian();
        locVaHienThiBieuDo();
        Date tuNgay = Date.valueOf(txtTuNgay.getText());
        Date denNgay = Date.valueOf(txtDenNgay.getText());
        hienThiBieuDoPieTheoNgay(tuNgay, denNgay);


    }//GEN-LAST:event_btnLocbtnLocActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // Gán giá trị vào combo khi mở form
        cboKhoangTG.removeAllItems(); // Nếu cần xóa cũ
        cboKhoangTG.addItem("Tùy chọn");
        cboKhoangTG.addItem("Hôm nay");
        cboKhoangTG.addItem("Hôm qua");
        cboKhoangTG.addItem("Tuần này");
        cboKhoangTG.addItem("Tháng này");

        cboKhoangTG.setSelectedItem("Hôm nay"); // Chọn mặc định là "Hôm nay"
        xuLyKhoangThoiGian(); // Cập nhật ngày luôn
        hienThiBieuDoBanChay();

        // Tự động hiển thị biểu đồ từ đầu tháng đến hôm nay
        LocalDate homNay = LocalDate.now();
        LocalDate dauThang = homNay.withDayOfMonth(1);

        Date tuNgay = Date.valueOf(dauThang);
        Date denNgay = Date.valueOf(homNay);

        hienThiBieuDoPieTheoNgay(tuNgay, denNgay);

        // Nếu bạn có set text cho txtTuNgay, txtDenNgay:
        txtTuNgay.setText(tuNgay.toString());
        txtDenNgay.setText(denNgay.toString());

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manhinhchinhadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manhinhchinhadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manhinhchinhadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manhinhchinhadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                manhinhchinhadmin dialog = new manhinhchinhadmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bieudo;
    private javax.swing.JButton btnLoc;
    private javax.swing.JComboBox<String> cboKhoangTG;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDenNgay;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblTuNgay;
    private javax.swing.JPanel pnlBieuDoBanChay;
    private javax.swing.JTextField txtDenNgay;
    private javax.swing.JTextField txtTuNgay;
    // End of variables declaration//GEN-END:variables

    public void hienThiBieuDoPieTheoNgay(Date tuNgay, Date denNgay) {
        try {
            String sql = "SELECT sp.TenSP, SUM(ctdh.SoLuong) AS TongSoLuong, "
                    + "SUM(ctdh.SoLuong * ctdh.DonGia) AS TongTien "
                    + "FROM ChiTietDonHang ctdh "
                    + "JOIN SanPham sp ON ctdh.MaSP = sp.MaSP "
                    + "JOIN DonHang dh ON ctdh.MaDH = dh.MaDH "
                    + "WHERE dh.Ngaylap BETWEEN ? AND ? ";

            // THÊM LỌC THEO LOẠI (nếu có chọn loại cụ thể)
            String selectedLoai = cboLoai.getSelectedItem().toString();
            boolean locLoai = !selectedLoai.equalsIgnoreCase("Tất cả");
            if (locLoai) {
                sql += "AND sp.MaLoai = ? ";
            }

            sql += "GROUP BY sp.TenSP";

            // Truy vấn
            ResultSet rs;
            if (locLoai) {
                // Lấy mã loại theo tên loại (nếu cần)
                String maLoai = getMaLoaiByTen(selectedLoai); // Hàm bạn tự viết, hoặc map
                rs = XJdbc.query(sql, tuNgay, denNgay, maLoai);
            } else {
                rs = XJdbc.query(sql, tuNgay, denNgay);
            }

            DefaultPieDataset dataset = new DefaultPieDataset();
            double tongTienTatCa = 0;
            int tongSoLuongTatCa = 0;

            while (rs.next()) {
                String tenSP = rs.getString("TenSP");
                int soLuong = rs.getInt("TongSoLuong");
                double tongTien = rs.getDouble("TongTien");

                dataset.setValue(tenSP + " (" + soLuong + " sp)", tongTien);
                tongTienTatCa += tongTien;
                tongSoLuongTatCa += soLuong;
            }

            String tieuDe = String.format("Từ %s đến %s - Tổng: %, .0f VNĐ - SL: %d SP",
                    tuNgay.toString(), denNgay.toString(), tongTienTatCa, tongSoLuongTatCa);

            JFreeChart pieChart = ChartFactory.createPieChart(
                    tieuDe, dataset, true, true, false
            );

            pieChart.getTitle().setFont(new Font("Arial", Font.BOLD, 18));
            pieChart.getLegend().setItemFont(new Font("Arial", Font.PLAIN, 14));
            pieChart.setBackgroundPaint(Color.WHITE);

            ChartPanel chartPanel = new ChartPanel(pieChart);
            chartPanel.setPreferredSize(new Dimension(500, 400));

            bieudo.removeAll();
            bieudo.setLayout(new BorderLayout());
            bieudo.add(chartPanel, BorderLayout.CENTER);
            bieudo.validate();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi hiển thị biểu đồ: " + e.getMessage());
        }
    }

    public String getMaLoaiByTen(String tenLoai) {
        try {
            String sql = "SELECT MaLoai FROM LoaiSanPham WHERE TenLoai = ?";
            ResultSet rs = XJdbc.query(sql, tenLoai);
            if (rs.next()) {
                return rs.getString("MaLoai");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public void locVaHienThiBieuDo() {
        try {
            String tuNgay = txtTuNgay.getText().trim();
            String denNgay = txtDenNgay.getText().trim();
            String loaiSP = cboLoai.getSelectedItem().toString();

            String sql = "SELECT sp.TenSP, SUM(ctdh.SoLuong * ctdh.DonGia) AS TongTien "
                    + "FROM ChiTietDonHang ctdh "
                    + "JOIN SanPham sp ON ctdh.MaSP = sp.MaSP "
                    + "JOIN DonHang dh ON ctdh.MaDH = dh.MaDH "
                    + "JOIN LoaiSanPham lsp ON sp.MaLoai = lsp.MaLoai "
                    + "WHERE dh.NgayLap BETWEEN ? AND ? ";

            boolean locTheoLoai = !loaiSP.equalsIgnoreCase("Tất cả");
            if (locTheoLoai) {
                sql += "AND lsp.TenLoai = ? ";
            }

            sql += "GROUP BY sp.TenSP";

            Connection conn = XJdbc.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, tuNgay);
            pstmt.setString(2, denNgay);

            if (locTheoLoai) {
                pstmt.setString(3, loaiSP);
            }

            ResultSet rs = pstmt.executeQuery();
            DefaultPieDataset dataset = new DefaultPieDataset();

            while (rs.next()) {
                String tenSP = rs.getString("TenSP");
                double tongTien = rs.getDouble("TongTien");
                dataset.setValue(tenSP, tongTien);
            }

            String tieuDe = locTheoLoai
                    ? "Doanh thu (" + loaiSP + ") từ " + tuNgay + " đến " + denNgay
                    : "Doanh thu từ " + tuNgay + " đến " + denNgay;

            JFreeChart pieChart = ChartFactory.createPieChart(
                    tieuDe,
                    dataset,
                    true, true, false
            );

            ChartPanel chartPanel = new ChartPanel(pieChart);
            chartPanel.setPreferredSize(new java.awt.Dimension(500, 400));

            bieudo.removeAll();
            bieudo.setLayout(new BorderLayout());
            bieudo.add(chartPanel, BorderLayout.CENTER);
            bieudo.validate();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi lọc dữ liệu: " + e.getMessage());
        }
    }

    private void xuLyKhoangThoiGian() {
        LocalDate homNay = LocalDate.now();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        String chon = cboKhoangTG.getSelectedItem().toString();
        LocalDate tu, den;

        switch (chon) {
            case "Hôm nay":
                tu = den = homNay;
                break;
            case "Hôm qua":
                tu = den = homNay.minusDays(1);
                break;
            case "Tuần này":
                tu = homNay.with(DayOfWeek.MONDAY);
                den = homNay.with(DayOfWeek.SUNDAY);
                break;
            case "Tháng này":
                tu = homNay.withDayOfMonth(1);
                den = homNay.withDayOfMonth(homNay.lengthOfMonth());
                break;
            default: // "Tùy chọn"
                return; // Không tự động thay đổi
        }

        txtTuNgay.setText(fmt.format(tu));
        txtDenNgay.setText(fmt.format(den));
    }

    public void hienThiBieuDoBanChay() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String sql = "SELECT sp.TenSP, SUM(ct.SoLuong) AS TongSoLuong "
                + "FROM ChiTietDonHang ct "
                + "JOIN SanPham sp ON ct.MaSP = sp.MaSP "
                + "GROUP BY sp.TenSP "
                + "ORDER BY TongSoLuong DESC";

        try (Connection con = XJdbc.getConnection(); PreparedStatement ps = con.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                String tenSP = rs.getString("TenSP");
                int soLuong = rs.getInt("TongSoLuong");
                dataset.addValue(soLuong, "Số lượng", tenSP);
            }

            JFreeChart barChart = ChartFactory.createBarChart(
                    "Top sản phẩm bán chạy",
                    "Sản phẩm",
                    "Số lượng bán",
                    dataset
            );

            barChart.getTitle().setFont(new Font("Arial", Font.BOLD, 18));
            barChart.getLegend().setItemFont(new Font("Arial", Font.PLAIN, 14));
            barChart.setBackgroundPaint(Color.WHITE);

            CategoryPlot plot = barChart.getCategoryPlot();
            plot.getRenderer().setSeriesPaint(0, new Color(0, 153, 255));
            plot.setBackgroundPaint(Color.lightGray);
            plot.setRangeGridlinePaint(Color.white);

            ChartPanel chartPanel = new ChartPanel(barChart);
            chartPanel.setPreferredSize(new java.awt.Dimension(pnlBieuDoBanChay.getWidth(), pnlBieuDoBanChay.getHeight()));

            pnlBieuDoBanChay.removeAll();
            pnlBieuDoBanChay.setLayout(new java.awt.BorderLayout());
            pnlBieuDoBanChay.add(chartPanel, java.awt.BorderLayout.CENTER);
            pnlBieuDoBanChay.validate();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
