/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.kho;

import maytinh.controller.QuanLyKhoController;
import maytinh.impl.QuanLyKhoControllerImpl;
import maytinh.entity.Kho;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * View class cho quản lý Kho theo mô hình MVC
 * @author Admin
 */
public class quanlykho extends javax.swing.JDialog {

    private QuanLyKhoController controller;
    
    /**
     * Creates new form quanlykho
     */
    public quanlykho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new QuanLyKhoControllerImpl();
        loadData();
        setTitle("Hệ Thống Quản Lý Kho - Warehouse Management System");
    }
    
    /**
     * Load dữ liệu ban đầu
     */
    private void loadData() {
        try {
            controller.loadData(jTable1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage(), 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panl = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttuptimkiemkho = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        btLichsuKho = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmahang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnamehang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        txtgiatien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttrangthai = new javax.swing.JTextField();
        txtthoigian = new javax.swing.JTextField();
        btxuatnhap = new javax.swing.JButton();
        BtXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên  sản phẩm", "Số lượng", "Giá tiền", "Trạng thái", "Thời gian Xuất Nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttuptimkiemkho.setText("Tìm kiếm");
        buttuptimkiemkho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttuptimkiemkhoActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        btLichsuKho.setText("Lịch sử Xuất Nhập");
        btLichsuKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLichsuKhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(buttuptimkiemkho)
                .addGap(32, 32, 32)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLichsuKho)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttuptimkiemkho)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btLichsuKho)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        panl.addTab("Danh sách Xuất Nhập Kho", jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Biểu Mẫu");

        jLabel2.setText("Mã Hàng");

        jLabel3.setText("Tên Hàng");

        jLabel4.setText("Số lượng");

        jLabel5.setText("Giá tiền");

        jLabel6.setText("Trạng Thái Xuất Nhập");

        jLabel7.setText("Thời gian Xuất Nhập");

        btxuatnhap.setText("Xuất Nhập");

        BtXoa.setText("Xóa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btxuatnhap)
                        .addGap(18, 18, 18)
                        .addComponent(BtXoa))
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txttrangthai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmahang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel6)))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(txtnamehang)
                            .addComponent(jLabel5)
                            .addComponent(txtgiatien)
                            .addComponent(jLabel7)
                            .addComponent(txtthoigian, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmahang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnamehang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgiatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtthoigian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btxuatnhap)
                    .addComponent(BtXoa))
                .addGap(99, 99, 99))
        );

        panl.addTab("Biểu mẫu Xuất Nhập", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panl)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panl)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // Tìm kiếm khi nhấn Enter với validation
        String keyword = jTextField7.getText().trim();
        if (controller.validateSearchKeyword(keyword)) {
            controller.timKiemKho(jTable1, keyword);
        }
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void buttuptimkiemkhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttuptimkiemkhoActionPerformed
        // Tìm kiếm kho với validation
        String keyword = jTextField7.getText().trim();
        if (controller.validateSearchKeyword(keyword)) {
            controller.timKiemKho(jTable1, keyword);
        }
    }//GEN-LAST:event_buttuptimkiemkhoActionPerformed
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) { // Double click
            layDuLieuTuBang();
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void btLichsuKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLichsuKhoActionPerformed
        controller.hienThiLichSu(jTable1);
    }//GEN-LAST:event_btLichsuKhoActionPerformed
    
    /**
     * Xử lý sự kiện nút Xuất Nhập với validation nâng cao
     */
    private void btxuatnhapActionPerformed(java.awt.event.ActionEvent evt) {
        String maHang = txtmahang.getText().trim();
        String tenHang = txtnamehang.getText().trim();
        String soLuong = txtsoluong.getText().trim();
        String giaTien = txtgiatien.getText().trim();
        String trangThai = txttrangthai.getText().trim();
        
        // Validation trước khi xử lý
        if (!controller.validateForm(maHang, tenHang, soLuong, giaTien, trangThai)) {
            return;
        }
        
        // Gọi controller để xuất nhập kho
        if (controller.xuatNhapKho(maHang, tenHang, soLuong, giaTien, trangThai)) {
        // Clear form và reload data
            controller.clearForm(txtmahang, txtnamehang, txtsoluong, txtgiatien, txttrangthai, txtthoigian);
        refreshTable();
        }
    }
    
    /**
     * Xử lý sự kiện nút Xóa với validation
     */
    private void BtXoaActionPerformed(java.awt.event.ActionEvent evt) {
        // Validation trước khi xóa
        if (!controller.validateDeleteOperation(jTable1)) {
            return;
        }
        
        if (controller.xoaKho(jTable1)) {
            refreshTable();
        }
    }
    
    /**
     * Xử lý sự kiện nút Lấy dữ liệu
     */
    private void btnLayDuLieuActionPerformed(java.awt.event.ActionEvent evt) {
        layDuLieuTuBang();
    }
    
    /**
     * Refresh dữ liệu bảng
     */
    private void refreshTable() {
        try {
            controller.loadData(jTable1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi làm mới dữ liệu: " + e.getMessage(), 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Hiển thị thống kê kho
     */
    private void showStatistics() {
        try {
            int totalRows = jTable1.getRowCount();
            int selectedRow = jTable1.getSelectedRow();
            
            StringBuilder stats = new StringBuilder();
            stats.append("Thống kê kho:\n");
            stats.append("- Tổng số bản ghi: ").append(totalRows).append("\n");
            
            if (selectedRow >= 0) {
                String maHang = (String) jTable1.getValueAt(selectedRow, 0);
                String tenHang = (String) jTable1.getValueAt(selectedRow, 1);
                stats.append("- Dòng được chọn: ").append(selectedRow + 1).append("\n");
                stats.append("- Mã hàng: ").append(maHang).append("\n");
                stats.append("- Tên hàng: ").append(tenHang).append("\n");
            }
            
            stats.append("- Dữ liệu được cập nhật lần cuối: ").append(new java.util.Date());
            
            JOptionPane.showMessageDialog(this, stats.toString(),
                "Thống kê", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi hiển thị thống kê: " + e.getMessage(), 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Lấy dữ liệu từ bảng và fill vào form với validation
     */
    private void layDuLieuTuBang() {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng từ bảng!", 
                "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Validation dữ liệu từ bảng
            Object maHangObj = jTable1.getValueAt(row, 0);
            Object tenHangObj = jTable1.getValueAt(row, 1);
            Object soLuongObj = jTable1.getValueAt(row, 2);
            Object giaTienObj = jTable1.getValueAt(row, 3);
            Object trangThaiObj = jTable1.getValueAt(row, 4);
            Object thoiGianObj = jTable1.getValueAt(row, 5);
            
            if (maHangObj == null || tenHangObj == null || soLuongObj == null || 
                giaTienObj == null || trangThaiObj == null) {
                JOptionPane.showMessageDialog(this, "Dữ liệu trong bảng không hợp lệ!", 
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Lấy dữ liệu từ bảng
            String maHang = maHangObj.toString();
            String tenHang = tenHangObj.toString();
            int soLuong = Integer.parseInt(soLuongObj.toString());
            String giaTienStr = giaTienObj.toString().replaceAll("[^0-9]", "");
            double giaTien = Double.parseDouble(giaTienStr);
            String trangThai = trangThaiObj.toString();

            // Validation dữ liệu trước khi fill
            if (maHang.trim().isEmpty() || tenHang.trim().isEmpty() || soLuong <= 0 || giaTien <= 0) {
                JOptionPane.showMessageDialog(this, "Dữ liệu trong bảng không hợp lệ để lấy!", 
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Fill vào form
            txtmahang.setText(maHang);
            txtnamehang.setText(tenHang);
            txtsoluong.setText(String.valueOf(soLuong));
            txtgiatien.setText(String.valueOf((int)giaTien));
            txttrangthai.setText(trangThai);
            if (thoiGianObj != null) {
                txtthoigian.setText(thoiGianObj.toString());
            }

            // Chuyển sang tab Biểu mẫu
            panl.setSelectedIndex(1);

            JOptionPane.showMessageDialog(this, 
                "Đã lấy dữ liệu từ bảng thành công!\n" +
                "Mã hàng: " + maHang + "\n" +
                "Tên hàng: " + tenHang + "\n" +
                "Số lượng: " + soLuong + "\n" +
                "Giá tiền: " + String.format("%,.0f VNĐ", giaTien) + "\n" +
                "Trạng thái: " + trangThai,
                "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi chuyển đổi dữ liệu số: " + e.getMessage(), 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu: " + e.getMessage(), 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlykho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlykho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlykho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlykho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                quanlykho dialog = new quanlykho(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtXoa;
    private javax.swing.JButton btLichsuKho;
    private javax.swing.JButton btxuatnhap;
    private javax.swing.JButton buttuptimkiemkho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTabbedPane panl;
    private javax.swing.JTextField txtgiatien;
    private javax.swing.JTextField txtmahang;
    private javax.swing.JTextField txtnamehang;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txtthoigian;
    private javax.swing.JTextField txttrangthai;
    // End of variables declaration//GEN-END:variables
}
